theme="dark_plus"
[editor]
bufferline="always"		

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"(" = "goto_prev_paragraph"
")" = "goto_next_paragraph"
"G" = "goto_file_end"
"0" = "goto_line_start"
"V" = ["goto_line_start","select_mode"]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-q" = ":buffer-close"
# "<space>q" = ":buffer-close"
g = { a = "code_action" } # Maps `ga` to show possible code actions

C-g = [
    # ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

[keys.select]
"(" = "goto_prev_paragraph"
")" = "goto_next_paragraph"
"G" = "goto_file_end"
"0" = "goto_line_start"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"

