# ~/.config/helix/languages.toml
[language-server.gpt]
command = "helix-gpt"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.wakatime]
command = "wakatime-ls"


[language-server.pyright.config]
typeCheckingMode = "basic"
autoSearchPaths = true
useLibraryCodeForTypes = true
reportMissingTypeStubs = "none"
reportUnknownParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportUnknownLambdaType = "none"
reportUntypedFunctionDecorator = "none"
reportPrivateUsage = "none"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportOptionalCall = "warning"

[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
language-servers = [ "pyright", "ruff","gpt","wakatime" ]
auto-format = true


[[language]]
name = "markdown"
language-servers = [ "gpt","wakatime" ]
auto-format = true

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "gpt","wakatime" ]
formatter = { command = "yamlfmt", args = ["-"] }
auto-format = true

[[language]]
name = "javascript"
file-types = ["js", "cjs", "mjs", "bic", "boc"]
language-servers = ["gpt","wakatime"]
