# ~/.config/helix/languages.toml
[language-server.gpt]
command = "helix-gpt"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]


[language-server.pyright.config]
typeCheckingMode = "basic"
autoSearchPaths = true
useLibraryCodeForTypes = true
reportMissingTypeStubs = "none"
reportUnknownParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportUnknownLambdaType = "none"
reportUntypedFunctionDecorator = "none"
reportPrivateUsage = "none"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportOptionalCall = "warning"

[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
language-servers = [ "pyright", "ruff","gpt" ]
auto-format = true


